# Generated by Django 3.1.2 on 2022-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='foodtype',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='foodtype',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
