# Generated by Django 3.1.2 on 2022-01-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220125_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='foodtype',
            new_name='style',
        ),
    ]
