# Generated by Django 3.1.2 on 2022-01-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220125_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='location', max_length=200),
        ),
    ]
