# Generated by Django 4.0.1 on 2022-02-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220125_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
