# Generated by Django 3.1.2 on 2022-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220224_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='style',
            field=models.CharField(default='Restaurant', max_length=30),
        ),
    ]
