# Generated by Django 3.1.2 on 2022-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_restaurant_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
