# Generated by Django 3.1.2 on 2022-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_restaurant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.ManyToManyField(help_text='tags', null=True, to='reviews.Tag'),
        ),
    ]
