# Generated by Django 3.1.2 on 2022-02-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220224_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='tags', null=True, to='reviews.Tag'),
        ),
    ]
