# Generated by Django 3.1.2 on 2022-02-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220224_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='typeOf',
            field=models.CharField(default='Restaurant', max_length=30),
        ),
    ]
