# Generated by Django 3.1.2 on 2022-02-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_restaurant_typeof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='typeOf',
        ),
    ]
