# Generated by Django 3.1.2 on 2022-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_remove_restaurant_typeof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
