# Generated by Django 3.1.2 on 2022-02-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20220224_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='description', max_length=500),
        ),
    ]
